# Generated by Django 2.0.3 on 2018-03-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='intro',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
